import { NextPage } from 'next';
import Head from 'next/head';

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>agros-fs-mini-test-fe</title>
        <meta name='description' content='Generated by Create Next Stack.' />
      </Head>
      <section>
        <h1>Haloo 2</h1>
      </section>
    </>
  );
};

export default About;
